<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>logo.ico</ApplicationIcon>
    <AssemblyName>AudioScheduler_v1.0.3</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.4" />
  </ItemGroup>

</Project>